import SETTINGS_NAMES from "./settingsNames";
import DEVICES_STATUS from "./devicesStatus";

const DEFAULT_DEVICES_STATUS = {
    [SETTINGS_NAMES.INPUT]: {
        [SETTINGS_NAMES.AUDIO_TYPE]: DEVICES_STATUS.PREPARE,
        [SETTINGS_NAMES.VIDEO_TYPE]: DEVICES_STATUS.PREPARE,
    },
    [SETTINGS_NAMES.OUTPUT]: {
        [SETTINGS_NAMES.AUDIO_TYPE]: DEVICES_STATUS.PREPARE,
        [SETTINGS_NAMES.VIDEO_TYPE]: DEVICES_STATUS.PREPARE,
    },
};

export { DEFAULT_DEVICES_STATUS };